language: python

services:
  - docker

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install paramiko coverage coveralls

script:
  - cd source && coverage run --source=. test_containeroso.py

after_success: coveralls
