FROM ubuntu:18.04

RUN apt-get update &&\
    apt-get -y install openssh-server iproute2 iputils-ping dnsutils net-tools nmap vim &&\
    rm -r /var/lib/apt/lists/*

RUN mkdir /var/run/sshd

RUN useradd -m virtuoso
RUN echo 'virtuoso:password' | chpasswd
RUN usermod -a -G sudo virtuoso
RUN usermod -s /bin/bash virtuoso

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
